### ISSUE TITLE
Explore using a grouping mechanism to avoid having to individually invite DA folks to events

### ISSUE THREAD

**Issue by jduss4** [18F/delivery-assurance#107]
When creating a new event for the DA team, such as project board refinement, we have to add multiple individuals and occasionally people get accidentally omitted! Let's look into the use of a google group (?) or similar functionality so that we can use that for managing event invites going forward.

**Comment by jduss4** [comment]
After speaking with @ccostino , it looks like we can open a ticket to create a google group, but then will have administrative power over its users. We've scheduled time to look into some of the specifics and I'll have a recommendation by Wednesday's stand-up to make to the group!

**Comment by jduss4** [comment]
[Documentation about Google Group in Insite](https://insite.gsa.gov/employee-resources/information-technology/do-it-yourself/google-workspace/google-groups?term=)

**Comment by kfoley-18F** [comment]
I suspect google groups are heavyweight and will have ownership challenges with GSA IT. 

Can we explore Github teams instead?

**Comment by jduss4** [comment]
After conversation in the DA meeting, I'm tagging in @MelissaBraxton to take ownership of this task!  🎉

**Comment by MelissaBraxton** [comment]
We have a GitHub team for repo access, but I think we still need a solution for folks accidentally being left off of calendar invites.  Currently inviting folks to needed mtgs is a manual, error prone task (each person has to be added and removed from each event or series), and is particularly onerous given how frequently people join and leave the group.   

I'm happy to move forward with the Google group for calendaring purposes and volunteer to be the initial steward of the group. 

@kfoley-18F  - How does this sound?  Does Jess' proposal work for you as a name? 

> 18F Service Delivery / 18f-service-delivery@gsa.gov 

If I get your 👍 , then I can move forward and request the group from GSA IT.

**Comment by kfoley-18F** [comment]
Service Delivery seems confusing to me  given the Service Design subteam within Design. 
I know it somewhat maps to GSA Service Delivery team as a template but seems like collisions are possible. 

18F-TLC? there was some discussion of "TLC team"

Aside from naming, I'm 👍 about the approach of having a Google group from GSA IT.

**Comment by MelissaBraxton** [comment]
Sounds good. I'm all for 18F-TLC!

Anyone else who should have a vote in whether we move forward with that name?

**Comment by kfoley-18F** [comment]
😆  the team was figuring out it's name as "DA team" was unpopular. 
Likely whatever gets picked for the group will stick.

**Comment by MelissaBraxton** [comment]
18F-TLC requested! Should be in place tomorrow.

**Comment by MelissaBraxton** [comment]
Still waiting on this request being fulfilled.

**Comment by abrouilette** [comment]
Still waiting, @MelissaBraxton?

**Comment by MelissaBraxton** [comment]
@abrouilette This moved to done last week!

**Comment by abrouilette** [comment]
What a happy coincidence: I also moved to _Done_ last week!
