### ISSUE TITLE
Set up workflow for adding new people to GitHub Teams

### ISSUE THREAD

**Issue by jduss4** [18F/delivery-assurance#108]
### A description of the work

There is a [Delivery Assurance GitHub team](https://github.com/orgs/18F/teams/18f-delivery-assurance) in the 18F org with varying permissions to several hundred repositories.

When a new person joins the DA team, they should be added to this team so that they can add / manage issues from various repositories and take part in the [project board](https://github.com/orgs/18F/projects/41/views/1).

Currently @kfoley-18F  and @abrouilette  are the maintainers of the GH team.  Proposal:

1. Kelsey or Alan add @MelissaBraxton and @alexbielen to the group as maintainers
2. Melissa and Alex will create and carry out an onboarding / offboarding task to add and remove people to the team weekly

Apologies for squishing two tasks into one issue

### Point of contact on this issue

@alexbielen @MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other
- [X] Being @abrouilette or @kfoley-18F because of their current maintainer powers
- [X] Being @alexbielen and @MelissaBraxton for their workflow brainstorming powers

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes, ideally, but it can continue to be managed by Kelsey and Alan if needed
- [ ] No

How much time do you anticipate this work taking?

2 hours

### Acceptance Criteria

- [x] Melissa and Alex have the ability to add and remove members to the DA GitHub team
- [ ] Maintainers understand how to add / remove people and how it fits into the onboarding / offboarding workflow
- [ ] Melissa and Alex have a plan to add / remove people weekly as the DA team membership changes

**Comment by kfoley-18F** [comment]
I've added @MelissaBraxton and @alexbielen to the team and granted maintainer status. 
I think the last part missing for AC is making sure they know what is needed to add/remove folks, and how it fits into onboarding/offboarding flow.

**Comment by MelissaBraxton** [comment]
I created [this new issue](https://github.com/18F/delivery-assurance/issues/117) to create on and off-boarding issue templates. An acceptance criteria is that these templates include check list items to manage granting and revoking access to all teams/groups/boards, etc.  

Once we have these checklists as GH issues, I'd propose:
every Monday -  create and work an onboarding issue for each incoming person 
every Friday -  create and work an offboarding issue for each person rolling off the team

If we want to move #117 forward to prioritized, I can try and have those templates in place by Friday. Is that enough of a plan to call this issue closed? 

Thoughts? @kfoley-18F and @alexbielen?

**Comment by MelissaBraxton** [comment]
With #117 to stand up new on/offboarding templates that include a checklist item to add/remove folks from the GH Team, + a documented expectation in our QB playbook that we'll create new on/offboarding issues every Friday, I think we can close this.
