### ISSUE TITLE
Expand the diversity of our avatar library

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/delivery-assurance#139]
## User story
As an 18F team member, I need more diverse avatars to use in my presentations so that I can more accurately represent the American public.

### Additional information about the request
- We could create new avatars/edit existing avatars to show:
	- Someone with an eyepatch
	- Someone with glasses
	- Someone with really curly hair
	- Someone with a hearing aid
	- Someone wearing a hijab
	- The top of a wheelchair or power chair behind someone
	- etc.
- We have avatars in the Sketch template showing older people, but they haven’t made it into the Starter Deck. We should export those and add them to the deck. 

## Background
This is a continuation of #91.
During our recent research sprint on #91, @katefisher808 and I heard a desire for more diverse avatars. This issue would cover adding/editing avatars and adding them to our [avatar starter deck](https://docs.google.com/presentation/d/1CXXvxBbVjO3LjIUwRYEbk8WHpsG0AJdUc6SI_jAZDNQ/edit?usp=sharing).
 [You can see our full recommendations in this slide deck](https://docs.google.com/presentation/d/1mkzDrt1uIBtsWA4qrXJ4HY2Ul5C-d5ScuQ1p0XqKEqU/edit?usp=sharing).

### Point of contact on this issue
@bpdesigns for vision questions, @katefisher808 and @melchoyce for research questions, and @cmajel for questions about the sketch file.

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Timeline 
Does this need to happen in the next two weeks?
- [ ] Yes
- [x] No

### How much time do you anticipate this work taking?
One week

## Acceptance Criteria
As an 18F team member, I can find and use a diverse set of avatars in my presentations to better represent the human experience and help promote empathy and inclusion amongst our partners.

**Comment by melchoyce** [comment]
Started working on some new avatars, located here: https://drive.google.com/file/d/1oLWqXS5nVq1KJBCx3Cnn8VH0zdLAClqs/view?usp=share_link

@katefisher808's going to pick this up from me! Next steps:
- Create a wheelchair symbol to use in the avatars
- Export the avatars
- Add the new avatars to the starter slide deck
- Write up a changelog in the Sketch file noting:
  - Minor hairstyle tweaks to avoid clashing with age lines and the hearing aid
  - The addition of a hearing aid and wheelchair
  - Anything else new or changed that comes up tomorrow
- Update the files in Drive

**Comment by katefisher808** [comment]
Posting an update on this one! 
Building on Mel's work, I'm exporting and compiling a new version of the [starter deck](https://docs.google.com/presentation/d/1Bq8blIzbWaJIwx_GFzCybkXZBZmbO6dQ--HQNuxPr-o/edit#slide=id.g22e21e452b1_0_162) with more options that represent people. 

The items I was unable to get to were:
- Export and upload avatars with the hearing aid (Mel, I think the file on the drive may not have your illustration)
- Mock-up a symbol for a wheelchair

@melchoyce when you're back on Monday, want to take a look at the file on the drive to make sure it's the latest one from you and possibly export a few avatars we can swap into the new starter deck linked above? Any other adjustments you'd make to the starter deck before we share with Christine and Ben for their final OK?

**Comment by melchoyce** [comment]
@katefisher808 and I reviewed this together on Slack, and fixed the hearing aid. She's added that in to the deck, which is updated in Drive now: https://drive.google.com/drive/u/0/folders/1MFGWlJ6Z1ZzIVXK0h0Xh8RsUiBZzYdbg

@cmajel @bpdesigns Can we have you two both review the [starter deck](https://docs.google.com/presentation/d/1Bq8blIzbWaJIwx_GFzCybkXZBZmbO6dQ--HQNuxPr-o/edit?usp=sharing)?

**Comment by MelissaBraxton** [comment]
@bpdesigns and @cmajel  - Both Mel and Kate moved off the TLC crew last week and won't be able to continue on this. I think we can call this done for now. Any concerns?

**Comment by bpdesigns** [comment]
Sounds good to me.

**Comment by cmajel** [comment]
Same!

**Comment by katefisher808** [comment]
Thanks all! I will add the comment from Ben into the open/no-status ticket that we have for keeping this work going! This was a fun issue to work on.

**Comment by bpdesigns** [comment]
Thanks @katefisher808!
