### ISSUE TITLE
Investigate tangential efforts in the same space

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#15]
**Point of contact on this issue**
@colinmurphy01 and @Sgtpluck

**Billable?**
- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
1 day

### A description of the work
DA Team is similar to current efforts that are sharing ownership of work across a group of people, including:

- Adventures in Coworking
- Writing Lab

let's review their documentation, processes, and meet with them in order to see if we can learn from their experiences.

### Acceptance Criteria

- [ ] As a DA Team member, I've discovered tactical improvements and strategic risks that we should consider implementing

**Comment by colinmurphy01** [comment]
Synthesis is here for now: https://docs.google.com/document/d/1BcGjZjQs0IBm-LHaGp0Jj9LOBE9bUsAGuAYcoup05R0/edit#heading=h.hoieubqiijas

Could be spun out as a separate doc.

**Comment by a-chappelear** [comment]
@colinmurphy01 [I made a ticket to put feedback into its own research doc](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=20682997) (will work on that today/tomorrow)

**Comment by colinmurphy01** [comment]
Sweet then I'll close this in favor of that ticket being the documentation ticket.
