### ISSUE TITLE
Create Delivery Assurance charter/onboarding document

### ISSUE THREAD

**Issue by Sgtpluck** [18F/delivery-assurance#2]
**Project Name**
Delivery Assurance

**A brief description of the work**
The Delivery Assurance team was conceptualized as a team that folks can onboard and ramp up quickly in order to get two week iterations of work done that contribute to the organizational priorities. As such, we need a resource for new team members to get up to speed quickly.

**Acceptance Criteria**
As an 18F staff member staffed to the Delivery Assurance team, I can look at the README of this repo and know what the team is about and how to be succesful with it.

**Timeline**
- [ ] Urgent deadline: Ex. EOD tomorrow (10/10/23)
- [x] Time-frame: EOD 2/10/23

**Indicate which, if any, priority this ask falls under**
- [ ] Know, share, use and evolve our best practices
- [x] Increase 18F’s operational resilience
- [ ] Deliver more value to the public through our projects

**Additional context**
Add any other context or screenshots about the ask.

**Comment by Sgtpluck** [comment]
WIP: https://docs.google.com/document/d/16wOkBawlllldjvpjgLLgIUzXL_vPNpMsbgDPdfeiLj4/edit#

**Comment by colinmurphy01** [comment]
I think we can close this? @Sgtpluck

**Comment by Sgtpluck** [comment]
@colinmurphy01 do it in the shared project board 😃
