### ISSUE TITLE
Strategy for helpwanted and microrequest requests and channels

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#20]
**Point of contact on this issue**
@abrouilette @kfoley-18F 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
2 weeks

### A description of the work

With the DA Team, we'd like to consider sunsetting the helpwanted and microrequest channel and routing those requests to the DA Team in Github. There are many open questions for this to happen, including:

- What types of requests get posted, are all of them in-scope for the DA Team?
- Should we sunset those channels?
- If channels stay up, how can work be represented in DA Team's backlog?
- If channels go down, how are out of scope requests managed? (like TTS-org help)
- If channels go down, what's the rollout strategy for this change? How are people notified, are open requests migrated to DA board, etc?

### Acceptance Criteria

- [x] [Review findings from the channel audit](https://github.com/18F/delivery-assurance/issues/37)
- [x] A proposal has been presented and discussed amongst team / stakeholders
- [x] A decision has been made to sunset or leave up those channels

**Potentially Out of Scope for this ticket**
- [x] If channels comes down, there is a plan in place for in-scope and out-of-scope requests
- [ ] If channels comes down, there is a strategy for rollout
- [ ] If channels comes down, the DA Team is ready to develop comms and this plan

**Comment by a-chappelear** [comment]
Pulled out the audit AC into its own ticket, https://github.com/18F/delivery-assurance/issues/37

**Comment by mgwalker** [comment]
I've drafted an initial proposal for folks to respond/react to. https://docs.google.com/document/d/1DgR5NPJGD6ND2xb-swNoc2XhicUwaz6y_0x6ME8a2Uw/edit#

**Comment by colinmurphy01** [comment]
I really like the suggestions in the proposal, @mgwalker . I know that @qmanderson1 has been working on an inventory and I'd like to see what has come out of that investigation. I bet she has thoughts on this as well. 

I'll find time to meet and discuss this as a group next week.

**Comment by mgwalker** [comment]
Augh! I didn't see the audit ticket. This draft doc is premature, in that case. We'll see if any of it ends up being useful, but my apologies to @qmanderson1 for jumping the queue. The audit will be super duper informative.

**Comment by mgwalker** [comment]
@qmanderson1 @ColinChambers22 On the assumption that I'm rolling off DA at the end of the day, I'm not sure what to do with this issue/doc. Is it at a point for broader team feedback? Time to hand it off to LT as our proposal?

**Comment by colinmurphy01** [comment]
Since you're rolling off, I can take it from here. I think next steps are:

- Discuss proposal as a DA team
- Discuss proposal with LT
- Edit/tweak based on feedback
- Scope a ticket for generating a comms plan and execute

**Comment by annepetersen** [comment]
[Related issue](https://github.com/18F/delivery-assurance/issues/21)

**Comment by colinmurphy01** [comment]
I have not made any progress on this so the steps above are still relevant to get this over the finish line.

**Comment by annepetersen** [comment]
Decision in 3/21 meeting: rename current #helpwanted to tts-helpwanted and create a new #18f-helpwanted

Today’s 18F LT ship will include this change and announce it also elsewhere

**Comment by mgwalker** [comment]
![An animated clip of a white woman looking into a room through shelves with an excited expression, captioned "Heck yes, amen!"](https://media.giphy.com/media/EJdJPvf0boRGGIYaWR/giphy.gif)
