### ISSUE TITLE
Offboarding to-dos

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#32]
**Point of contact on this issue**
@a-chappelear @kfoley-18F 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
1 week

### A description of the work

As the DA Team members finish out their time, what's a checklist for offboarding?

### Acceptance Criteria

- [ ] Checklist is clear
- [ ] Checklist can be used as a template for when teammates offboard
- [ ] Work or knowledge lost is minimal

**Comment by a-chappelear** [comment]
Not sure if I leave this week or next couple - but! I can work on this (w/ some input from @colinmurphy01) since we might be next to offboard

**Comment by a-chappelear** [comment]
In our “drafts” folder [I have a document where I started to make an offboarding checklist ](https://docs.google.com/document/d/1vYbG8RclSP7-ebSsklRqs35TLOzCFYfdLs2ZZCCfffM/edit?usp=sharing)
- but midway realized, it may be more about defining the state of the project board (and how to handle tickets)

It’s currently in 2 parts, the start of a checklist for leadership for on/offboarding _(@colinmurphy01  did an awesome job walking new folks through the work - may want to capture some of that as tips for others?)_

And then I put together what I think is typical for closing or handing over an in-progress ticket. Most of this likely needs some group discussion. :)

Next step after reviewing those processes,  adding everything minus the leadership section to the ReadMe.

**Comment by colinmurphy01** [comment]
Pull Request #52 

Once merged we'll try it out with this cohort which is a sizeable group

**Comment by colinmurphy01** [comment]
Instead of creating checklists, after discussing with @abrouilette yesterday, we figured automated slackposts are a better self-service method for onboarding into the team. Alan can then check-in with people as needed.

[Draft posts](https://docs.google.com/document/d/1EetFjtho67McYrpOhsZ78wsihDq-f3TwCC5K_kX4-Mc/edit#heading=h.pj1nipl6ogs)

**Comment by colinmurphy01** [comment]
Added reminders to slack.
