### ISSUE TITLE
Slack integration with github board

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#35]
**Point of contact on this issue**
@Sgtpluck 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
1 day
### A description of the work

To make it easier for 18F employees to submit an issue to the DA Team. You could probably create a slack workflow that is a form that, when you fill out the form, it opens a ticket on the delivery assurance github repo.

### Acceptance Criteria

- As an 18F employee, I can easily submit a ticket with the necessary info
- As a LT member, I have the information needed to prioritize the ticket
- As a DA Team member, I have the information need to pick up the ticket

**Comment by mgwalker** [comment]
Slack's workflow builder is pretty limited. It can't be used to create GitHub issues, as far as I can tell. That would require a custom integration (such as adding new functionality to Charlie).

Built into Slack, there is a feature where you can turn a message into a GitHub issue by clicking the three vertical dots next to the message, then clicking "More message shortcuts...", and finally clicking the "Create GitHub issue" option. It's not a super clean process, though.

**Comment by colinmurphy01** [comment]
That's really helpful, thanks @mgwalker. Let's close this for now, clarify how we want people to submit issues first (#20), and then figure out how to make it easier.
