### ISSUE TITLE
Audit of #helpwanted & #microrequests

### ISSUE THREAD

**Issue by a-chappelear** [18F/delivery-assurance#37]
### A description of the work

[See ticket #20 for background](https://github.com/18F/delivery-assurance/issues/20)

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

How much time do you anticipate this work taking?
A sprint

### Acceptance Criteria

- A current state analysis has been conducted of the slack channels #helpwanted and #microrequests
- Identify common types of requests
- May be useful to review replies to see if requests often require discussions and input from others (ie. if those requests move to require a ticket to address, what's the good/bad impact) crowdsourced help vs ticketed
- Are there other channels where similar help requests filter in from?

**Comment by qmanderson1** [comment]
I can co-work with someone on this.

**Comment by a-chappelear** [comment]
Added what I could to #microrequests w/ some comments added to the questions tab.

**Comment by qmanderson1** [comment]
[Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1Ae5kvjulfBI1f2m11Q_1r3sc6UPLGOAEe1trtaXYsYI/edit#gid=0) with a detailed breakdown of recent #helpwanted and #microrequests by description, type of human needed, billability and date. [Here is our proposal](https://docs.google.com/document/d/1DgR5NPJGD6ND2xb-swNoc2XhicUwaz6y_0x6ME8a2Uw/edit#) which is also a response to a separate issue owned by @mgwalker as it relates to sunsetting the #helpwanted and #microrequest channels.  There is some overlap with the two issues so it's worth dropping both docs here for review.
