### ISSUE TITLE
Make an initial structure/outline of Delivery School

### ISSUE THREAD

**Issue by kfoley-18F** [18F/delivery-assurance#38]
**Project Name**
Make an initial structure or deeper outline of Delivery School 

**A brief description of the work**
The goal for this slice of work for the Delivery School as done by the DA Team is to assemble some structure in the google doc below from existing 18F content and resources that we can use for testing with project teams and start to build alignment on around 18F and talk about paths forward for D-School.
[This google doc draft has all the details for this activity](https://docs.google.com/document/d/14MT5mmqFq5rCUY1-ef8RLNdo22uXwTBNDy6DfgjhM20/edit#heading=h.c3whcxanvmli)

**Billable?**
- [ ] Yes
- [X] No
If yes, tock code:

**Point of contact(s)**
@kfoley-18F 

**Acceptance Criteria**
The google doc has been filled out with a few more levels of detail and some links and resources. 

**Timeline**
- [ ] Urgent deadline: Ex. EOD tomorrow (10/10/23)
- [X] Time-frame: End of Week

**Indicate which, if any, priority this ask falls under**
- [X] Know, share, use and evolve our best practices
- [ ] Increase 18F’s operational resilience
- [ ] Deliver more value to the public through our projects

**Skills needed**
- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Additional context**
Add any other context or screenshots about the ask.

**Comment by janelx** [comment]
@janelx todo:
- [ ] - [ ] schedule kickoff/planning meeting with assigned DA team
- [ ] schedule check-in with @kfoley-18F to review plan/work

**Comment by katefisher808** [comment]
Linking the two primary working docs here:
- [Epic overview](https://docs.google.com/document/d/1UWyX4E26BOFaDCt_nP_tIMjDwPzvjq-dW4_YGOttoaY/edit#)
- [Content outline](https://docs.google.com/document/d/1-yPhvggQLzeGJBmbLRa5MHoXtSCmJTw68Es7ZcIUayI/edit#)

**Comment by janelx** [comment]
Deliverable: 18F documentation organized into Delivery School structure is the [content outline here](https://docs.google.com/document/d/1-yPhvggQLzeGJBmbLRa5MHoXtSCmJTw68Es7ZcIUayI/edit#heading=h.21rnprk0d00)
