### ISSUE TITLE
Onboarding Greg Walker

### ISSUE THREAD

**Issue by colinmurphy01** [18F/delivery-assurance#41]
### Onboarding

Welcome to the team! Below is a list of things to do or confirm.

**Point of contact on this issue**
@abrouilette 

**Onboarding Checklist**
- [x] Review our [README](https://github.com/18F/delivery-assurance/blob/main/README.md)
- [x] Review [the Charter](https://github.com/18F/delivery-assurance/blob/main/docs/charter.md)
- [x] Review the work **On-Deck** in [our project board](https://github.com/orgs/18F/projects/41) for anything that interests you.
- [x] Confirm you can assign this ticket to yourself. If not, reach out to alanb on slack to ensure you have access.
- [x] Feel free to pick up an issue that interests you.
- [ ] If questions come up during your onboarding, add them to [our questions board](https://docs.google.com/spreadsheets/d/1J8cAcuE2zgpIFSJx_mKOjNmAcQGeYtQbz2vkTuqGI4U/edit#gid=1340104815)

**Comment by mgwalker** [comment]
@colinmurphy01 The links to the README and the charter are the same. Should they be?

**Comment by colinmurphy01** [comment]
Nope: 
- [README](https://github.com/18F/delivery-assurance/blob/main/README.md)
- [Charter](https://github.com/18F/delivery-assurance/blob/main/docs/charter.md)

**Comment by mgwalker** [comment]
I'm going to go ahead and close this one, I think?
