### ISSUE TITLE
Create a GitHub Team for the 18F Delivery Assurance team

### ISSUE THREAD

**Issue by mgwalker** [18F/delivery-assurance#46]

**Comment by mgwalker** [comment]
Created a team: https://github.com/orgs/18F/teams/18f-delivery-assurance/members

**Comment by colinmurphy01** [comment]
Reviewed list for based on current team and it looks good. Any other things you need someone to review?

Should we note this group in the README?

**Comment by mgwalker** [comment]
Yes! Great idea. Otherwise I think this is ready to go?
