### ISSUE TITLE
Create debrief template for Guides + Methods card sorts

### ISSUE THREAD

**Issue by dluetger** [18F/delivery-assurance#62]
### A description of the work
Create a short debrief template future delivery assurance team members can use to easily complete the card sorts from tickets [59](https://github.com/18F/delivery-assurance/issues/59) and [60](https://github.com/18F/delivery-assurance/issues/60).

### Point of contact on this issue
@dluetger @annepetersen 

**Billable?**

- [ ] Yes
- [X] No

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
1-2 hours

### Acceptance Criteria

- [ ] There is a 3-4 question worksheet that can be used as a standard for future Guides + Methods card sort debriefs
- [ ] If you were a researcher coming into this cold, is this a worksheet that would be useful and understandable to you?

**Comment by dluetger** [comment]
[Template for review](https://docs.google.com/document/d/161xEQNyO9ORvVCdBrGDdAzIqLGadNZem-yjAroTVQpQ/edit)

**Comment by melchoyce** [comment]
Who would be the best person to review this @dluetger?

**Comment by dluetger** [comment]
I think anyone with user research experience or experience being in research debriefs is appropriate here. Bonus points for having knowledge of the G+M project or interest. Looking to 1) verify this feels like what's advertised on the tin, and 2) get light to medium corrections or suggestions for content and clarity

**Comment by melchoyce** [comment]
From a clarity perspective, this looks good to me.

**Comment by katefisher808** [comment]
Looks great. Only thing I wonder is if this response from Kelsey on a different guides/methods ticket applies here too. Or if these tickets are in direct pursuit of that effort. https://github.com/18F/ux-guide/issues/255#issuecomment-1495029926

**Comment by katefisher808** [comment]
A few other prompts that could be good to add, depending on how the card sort prompts are defined:
- What questions did the participants ask during the card sort?
- What assumptions did the participants make during the card sort?
- What other ideas or suggestions did the participants have in support of guides and methods?
- What drove the participant's card sort IA? What goals can someone accomplish with the updated IA?

**Comment by MelissaBraxton** [comment]
@kfoley-18F  - Thinking this should move to the icebox?

**Comment by dluetger** [comment]
@MelissaBraxton Oh it's basically done I just need to briefly incorporate the feedback.

**Comment by MelissaBraxton** [comment]
Ok cool. Can we expect this will move to done in the next day or two?

**Comment by dluetger** [comment]
Yep!
