### ISSUE TITLE
Document how the Delivery Assurance team uses GitHub

### ISSUE THREAD

**Issue by melchoyce** [18F/delivery-assurance#67]
### A description of the work
Document how the DA team uses our project board, including details such as:
- Who can create a new issue on our board
- How, when, and by whom are new issues triaged and prioritized
- A brief explanation of how we use labels, and if relevant, milestones
- How people are assigned to specific issue
- What each column means
- What needs to happen in order for an issue to move from one column to another column, and who makes that decision
- What review is needed before an issue is done, and who should be tagged in reviews
- What happens when an issue is blocked, and how to proceed

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?

~1 hour, more depending on if it needs to become a conversation.

### Acceptance Criteria

- [ ] A new DA member can read the documentation around how to use our GitHub project, and understand what to do next.

**Comment by colinmurphy01** [comment]
[Google doc for drafting guidance](https://docs.google.com/document/d/1bch6NyutXZ1hpm8KrMtN--257n82pu4eljT4sNN8G4I/edit)

**Comment by melchoyce** [comment]
Our draft is now ready for review: https://docs.google.com/document/d/1bch6NyutXZ1hpm8KrMtN--257n82pu4eljT4sNN8G4I/edit#heading=h.dl7rd1uqchi6

Looking for accuracy, content suggestions and copy edits.

**Comment by melchoyce** [comment]
Assigned @abrouilette for review.
