### ISSUE TITLE
Set-up Delivery Assurance in the 18F dashboard for knowledge management and project health tracking

### ISSUE THREAD

**Issue by katefisher808** [18F/delivery-assurance#72]
Timeline
Does this need to happen in the next two weeks?
No

How much time do you anticipate this work taking?
Less than a day

Background
The Delivery Assurance project needs to be added to the [18F Dashboard](https://airtable.com/appsLLLryeqBK2V9d/tblRHYBJtIZOxImMd/viwxpzlw7ZzToe8T9?blocks=hide) for ongoing knowledge management and project health tracking. 

Acceptance criteria (we'll know we're done when…)

- [ ] The project is added to the dashboard

**Comment by colinmurphy01** [comment]
Scheduled time with Rebecca to do this on 3/10
