### ISSUE TITLE
Recreate Daily Ship template

### ISSUE THREAD

**Issue by melchoyce** [18F/delivery-assurance#75]
### A description of the work
The [Weekly Ship template linked in the resource guide](https://docs.google.com/document/d/1ulPzFvBLunXm3MD0xL8nPzlJDOoFJbNLPo0Sl6ph99Q/edit?usp=drivesdk) is giving me a “does not exist” error. [This has been a problem](https://gsa-tts.slack.com/archives/CHZLJBWCV/p1657034382432909) [for months](https://gsa-tts.slack.com/archives/C4HHJH1C2/p1657311962710719) and [we have not gotten a resolution](https://gsa-tts.slack.com/archives/C4HHJH1C2/p1617984170001300) on it.

We should recreate the template and update the link in the resource guide.

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
One hour

### Acceptance Criteria

- [x] A new weekly ship template exists
- [ ] It has been submitted to the resource library

**Comment by melchoyce** [comment]
First draft is done:

https://docs.google.com/document/d/1hb7Ugcx_N0l97D65pCsNn2LJii0G92RLHsDT7IeyFmc/edit?usp=sharing

Questions:

1. Where should the final template live?
2. Is the content clear?
3. Is there any content missing?
4. Does it need to include this "[Front Matter](https://docs.google.com/document/d/1UkvUiaYnusqVoYku0-fhzImg6Ir56k6fu7JYSLLmehE/edit)" card at the beginning?

**Comment by annepetersen** [comment]
1. There is a [project resources folder](https://drive.google.com/drive/folders/1L9qqS6-b-emvlWJ4JPCG58LW62bbV361) and [Process: 18F team-internal subfolder](https://drive.google.com/drive/folders/1vKkKrgbtOhfDOpxvfu_4AyVETLQVfs9O). Probably there? 
2. Director of Account Management, I'd guess
[will look at 3-4 separately and comment in-doc]
5. Yes, according to [Contributing to project resources](https://docs.google.com/document/d/1u4r2o9hFPHbR0DmDPSkYsWJgSWxmQtuNBp7odkXJoX8/edit)
