### ISSUE TITLE
Update 18F icon packs

### ISSUE THREAD

**Issue by cmajel** [18F/delivery-assurance#81]
### A description of the work
18Fers use our icon set regularly to create clear, effective communications with partners, executive sponsors, and internal teams. These icons need updates to keep presentations polished and to meet the needs of teams using these assets.

#### Maintenence items

Review existing [icon sets](https://brand.18f.gov/icons/) and [slide starter packs](https://docs.google.com/presentation/d/11E9IBb1JkNWz5FLkipXJCmhtKJQa2EL3h0W3EqPZYNQ/edit#slide=id.g5ecdbbee9e_0_0).

- Review and fix end caps
Here's an example on the `zoom-out` icon export: where the handle meets the glass, the end cap should not be visible; but instead it is rounded and sticks out.
![zoom-out](https://user-images.githubusercontent.com/2374206/224725454-02d1ee51-3cd0-4a36-ae5a-158807087824.png)
- Add 18F dark blue export to downloads (#1C304A)
- Update [downloads](https://brand.18f.gov/icons/) on 18F identity site (sketch files, exports, sticker sheets), [slide starters](https://docs.google.com/presentation/d/11E9IBb1JkNWz5FLkipXJCmhtKJQa2EL3h0W3EqPZYNQ/edit#slide=id.g5ecdbbee9e_0_0), and [18F deck template](https://brand.18f.gov/templates/) as needed
- Note additional issues as needed. The team should feel empowered to reorganize and adjust assets so that they work better.

#### Bigger evaluation items, as time allows

- What’s people’s experience using these shared assets in presentations?
- What do people need that we don’t have?
- What visualizations are missing?

### Point of contact on this issue
You can reach out to me (@cmajel). For questions about updating the 18F brand site and templates, @igorkorenfeld can also assist.

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [x] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
- Maintenance issues I suspect would be about two weeks. 
- Evaluation items would require more time, and could be separated into additional tickets.

### Acceptance Criteria

- [ ] 18Fers can access updated icons through [downloads](https://brand.18f.gov/icons/) on 18F identity site (sketch files, exports, sticker sheets), [slide starters](https://docs.google.com/presentation/d/11E9IBb1JkNWz5FLkipXJCmhtKJQa2EL3h0W3EqPZYNQ/edit#slide=id.g5ecdbbee9e_0_0), and [18F deck template](https://brand.18f.gov/templates/)

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by HannaSChang** [comment]
@cmajel I've been updating the icons in Sketch but do you think it would be beneficial to have these icons in Figma as well (assuming they're not already in Figma)?

**Comment by melchoyce** [comment]
Yeah, agreed—I think it would be good to push these as-is in Sketch and provide the updated exports of all the colors, then once that's done, think about Sketch vs. Figma (or even Illustrator—what's the license situation there?). I think there's more questions we'd want to answer around long term maintainability of the icon set like what you've laid out, @cmajel.

**Comment by HannaSChang** [comment]
Thank you @cmajel and @melchoyce for your thoughts/feedback! I personally haven't used Sketch in over 3 years (ever since I started using Figma) so I was curious to know if that's the case here at 18F and wondered if it might be more convenient/faster for team members to pull the icons directly from Figma, but we can definitely table this for now and have a future discussion for using Sketch vs Figma vs Illustrator.

**Comment by melchoyce** [comment]
FWIW—I tend to drop the exported svg files directly into Figma when I need them 🤷 I don't even have a Sketch license

**Comment by HannaSChang** [comment]
@cmajel 18F Icon Packs have been updated and are ready for your review. Updated icons, sticker sheets, slide starters, and notes can be found below:

[Notes related to 18F Icons ticket](https://docs.google.com/document/d/1fa2lqQshvnm8hgY06q3ZF9PvHSmSiDhzFKoipuKZd0w/edit?usp=sharing)

[Updated Sketch, PNG/SVG files, and Sticker Sheets](https://drive.google.com/drive/folders/1R_xc7ae4GW7-Ni2fIy0mfRDwkTJvED5y?usp=share_link)

[Updated Icon Slide Starters](https://docs.google.com/presentation/u/0/d/14TeXdTAM0HXoMbciFjh5jHXMmtZYeh5CxIIuGBVxGek/edit)

Once everything is approved, I'll replace the old/current slide starter with the new one, and I'll work with one of the engineers on staff to update the links on 18F's visual identity site.

**Comment by cmajel** [comment]
Thank you @HannaSChang!

A few notes:
* In the png/svg exports I see some duplicates (e.g. there are three exports names `arrow-down-left.png`) Can you clean these up?
* This may be what you mean, but I'd suggest updating the existing icon starter deck with your slides (because that's what's linked from the 18F template, and may be pinned by people already). 
* Where would you recommend documenting that these changes happened? There's a (lightly populated) changelog in the sketch file. We could update that, or maybe move this to a readme in the download? What do you think?
* And yes to pairing on updating the site! Here's [the brand site repo](https://github.com/18F/brand) if you'd like to poke around.

**Comment by HannaSChang** [comment]
@cmajel That's so weird that there are duplicates! I don't know why that happened because there are no duplicates in my folder (see screenshot) hmmmm. I'm going to try compressing the folder and uploading that so hopefully that'll resolve the whole duplicate issue that you're seeing?

![Image](https://user-images.githubusercontent.com/127547918/229196944-f4d87ac3-6a81-4c52-824c-f4ae10bedb96.png)

Yes, to updating the existing icon starter deck. I just didn't want to mess with the original slides while people may still be trying to use it. :) 

I'll include an update to the changelog in Sketch! Thank you for pointing that out!

Thank you, Christine! I'll get back to you soon once I make these changes!

**Comment by melchoyce** [comment]
I'm seeing duplicates in the Black and Dark folders:

![Screen Shot 2023-03-31 at 2 17 31 PM](https://user-images.githubusercontent.com/2846578/229198911-f62011c1-2725-452d-9ad4-e7c421ba8455.png)

**Comment by HannaSChang** [comment]
@cmajel and @melchoyce Yeah, something funny happened when I imported my files into Google Drive so I decided to compress the files to avoid the duplicates from happening. 

I also updated the changelog in the Sketch file to include the changes that've been made. 

The updated compressed icons and updated Sketch file can be found in the [same folder here](https://drive.google.com/drive/folders/1R_xc7ae4GW7-Ni2fIy0mfRDwkTJvED5y?usp=share_link).

If you see anything else please let me know! Thank you both! :D

**Comment by cmajel** [comment]
👍 Updates look good to me!

**Comment by HannaSChang** [comment]
Thank you @cmajel! Will be working with @geekygirlsarah to update the links.
