### ISSUE TITLE
18F project reflection templates aren't a good match for internal projects

### ISSUE THREAD

**Issue by kfoley-18F** [18F/delivery-assurance#83]
### A description of the work
As we take on some internal initiatives, we need to be running regular project reflections. 
But our project reflection template for external projects doesn't always fit the context/circumstances well. We need a project reflection template for internal-to-18F projects. Maybe this looks more like a retro with stakeholders. The goals are increasing alignment and finding productive paths forward. 

### Point of contact on this issue
@SelenaJV as person wearing the CoD hat

### Reproduction steps (if necessary)
Current templates are here: 
https://docs.google.com/document/d/1mRz7I1vU6BDCd5ZvG5YRhKJ3XJSQ9oH-Y18cDlD-lMg/edit#heading=h.7qhkxz4rbjda
and 
https://docs.google.com/document/d/1ro-k8XCeyclOlsT9ugwLWaRMojKhW7QP445XnPuKdqo/edit#heading=h.559ehtm19kwy

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ X] No

How much time do you anticipate this work taking?
A week, perhaps? It likely is best done by several humans with different skills. 

### Acceptance Criteria

- [ ] What does "done" look like?

A set of project reflection summary/facilitation guides exist for internal projects, in the same place as the external templates. 
These templates have been shared out with 18F for use and iteration over time.

**Comment by lauraGgit** [comment]
@kfoley-18F when this gets picked up can i have some convos with folks about where the templates are at, what is needed?

**Comment by kfoley-18F** [comment]
Definitely!

**Comment by colinmurphy01** [comment]
I'd also be willing to be a SME on this after facilitating these internal reflections:

- [TTS DevTools](https://docs.google.com/document/d/1e0XJ7jF4kjdEoM_D87QZdYAR-qAs7crxlPJ1iXB2Afo/edit#heading=h.2prttxpyelbe)
- [18F Intake](https://docs.google.com/document/d/11Jyxi2Epm8SePXrrfd_mh--vHT6tJd0yNC39mWXIEAk/edit#heading=h.erx2j3hle7fk)

**Comment by dluetger** [comment]
@colinmurphy01 @lauraGgit Kate and I will try to grab some time with you this week

**Comment by annepetersen** [comment]
#103 may be a good opportunity to try a new template (or just iterated prompts) out in the next few weeks.

**Comment by katefisher808** [comment]
**Update on progress from @dluetger and myself on [short discovery](https://docs.google.com/document/d/1w_gWVA2OmFhyIzTLUmvgr1w1nKBzniFgUKLEX7Axw3Y/edit#):**
- We held discovery conversations to better understand the context for request
- We conducted a scan of four internal reflections and identified what was changed across them
- We reviewed other project reflection templates from the past
- We reviewed the updated strategic planning presentation from last week to inform outcome list

**Key changes made to the notes and summary templates:**
- Adjusted the notes and the summary template so it can be used on both internal and external projects, as well as for both in-flight and final-reflections
- Grouped the outcome list around the three strategic bets, and added additional detail based on the strategic planning updates from leadership
- Adjusted terminology in a few places to allow for both internal and external project application
- Made the framing of the summary prompts consistent

**Next steps for review of this ticket:**
- Share the draft templates with with Colin for initial review
- Set-up time with Kelsey or other stakeholders to walk through the updated templates, specifically the outcomes list
- Close this ticket

**Next steps for this work overall:**
- Test initial changes in upcoming TTS Dev Tools reflection
- Open new tickets for any additional changes to be made, or changes to be tested such as the outcomes list

**Comment by kfoley-18F** [comment]
@katefisher808 and @dluetger -

Please note from the original ticket: 
@SelenaJV as person wearing the CoD hat

If you haven't talked with Selena about this yet, please get on her calendar. 
She's asked to give input on this.

**Comment by katefisher808** [comment]
Updates on this issue: 
- We made a few additional changes to the templates based on the follow-up conversations with Colin, Kelsey, and Laura
- We cleaned up the google drive root folder, facilitation guide, so that the new templates are connected and visible
- We set up time to talk with Selena about the overall summary and get final feedback to inform new issues
- We set up draft issues based on the insights from the work: [Issue 134: Point people to the new project reflection template](https://github.com/18F/delivery-assurance/issues/134), and [Issue 136: Explore improvements to project close-out process](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25365562)


@kfoley-18F
