### ISSUE TITLE
Join TTS styling updates

### ISSUE THREAD

**Issue by rrefoy** [18F/delivery-assurance#99]
### A description of the work

On [Join TTS](https://join.tts.gsa.gov/), Talent needs someone who is familiar with markdown and possibly jekyll templates to make updates to the Upcoming positions section of their website. The Upcoming info sessions is overshadowing the actual job description and Talent is requesting styling assistance to improve the usability. Screenshot below for reference. 

<img width="688" alt="Screen Shot 2023-03-24 at 9 32 38 AM" src="https://user-images.githubusercontent.com/17129887/227594295-50ca736e-5af4-4540-9ddb-f8eccf51c394.png">

### Point of contact on this issue
@LeighFinkel 

### Reproduction steps (if necessary)
N/A

**Billable?**

- [x] Yes
- [ ] No
If yes, tock code: 1806

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes, Talent would like this to be updated by early next week which I'm going to decide ends on Wednesday at Noon PST 3/29.
- [ ] No

How much time do you anticipate this work taking?
1-5 hours, this **should not be** an overhaul of this section but rather purposefully a quick fix for usability.

### Acceptance Criteria

- [ ] What does "done" look like?

 As an prospective applicant, it is clear where to find the job description for a specific role and the upcoming info sessions for that role so that I know what the role entails and when I can attend to learn more.

**Comment by LeighFinkel** [comment]
Hi, I wanted to check in on the status of this request. I will be out this Thursday through Tuesday and am wondering if anyone can assist with this minor font change before I leave.

**Comment by melchoyce** [comment]
I can take on design improvements if an engineer can handle implementation.

**Comment by annepetersen** [comment]
Sure can: thank you!
